language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eyelin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eyelin/react-test npm run test

#construir las versiones de produccion
after_success:
  - docker build -t eyelin/multi-client ./client
  - docker build -t eyelin/multi-nginx ./nginx
  - docker build -t eyelin/multi-server ./server
  - docker build -t eyelin/multi-worker ./worker

  #log in en docker CLI, pero no podemos poner nusta cosntaseña en texto plano
  #tenemos que encriptarlas para que solo travis las vea
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #exportar las imagenes a Docker Hub
  - docker push eyelin/multi-client
  - docker push eyelin/multi-nginx
  - docker push eyelin/multi-server
  - docker push eyelin/multi-worker
